# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReflectApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReflectApp

  target 'ReflectAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReflectApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReflectApp-tvOS

  target 'ReflectApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
